# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/blog/:title"
# relative_permalinks: true

highlighter: rouge

timezone: America/Los_Angeles

# Default YAML frontmatter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true


# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""


# Image settings
image_base:          /public/images/

# Do not copy these file to the output directory
exclude: ["transfer.sh", README.md, "codepg/", "drafts/"]

#fb_appid:           337414769782635

# Setup
title:               Sai Teja Pratap
url:                 "https://yesteapea.com"
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sai Teja Pratap
  url:               https://twitter.com/yesteapea


# Google sitemap generation
gems:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num"


# Conversion
markdown:    redcarpet
excerpt_separator: "<!--break-->"

redcarpet:
  extensions: ["footnotes"]

kramdown:
  auto_ids: true

pages_list:
  Blog: '/blog/'
  Quotes: '/quotes/'
  Bookmarks: 'http://bm.yesteapea.com'


picture:
  source: "assets/imgs/_fullsize"
  output: "generated"
  markup: "picture"

